// Js2n.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (Js2n.tlb) that will become a resource in
// Js2n.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(7E829C5E-6093-4e3d-9622-7BC829D3EB65), version(1.0),
  helpfile("Js2n.hlp"),
  helpstring("Js2n ActiveX Control module"),
  control ]
library Js2nLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CJs2nCtrl

	[ uuid(DB94C377-4B82-4cac-B5C6-B927ABCE6E52),
	  helpstring("Dispatch interface for Js2n Control")]
	dispinterface _DJs2n
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
	};

	//  Event dispatch interface for CJs2nCtrl

	[ uuid(6FCA21FB-78E6-4825-8319-5C8285AE08CA),
	  helpstring("Event interface for Js2n Control") ]
	dispinterface _DJs2nEvents
	{
		properties:
			//  Event interface has no properties
		methods:
			[id(1)] void Js2nEvent(BSTR strEventType);
	};

	//  Class information for CJs2nCtrl

	[ uuid(C802F39D-BF85-427a-A334-77E501DB62E9),
	  helpstring("Js2n Control"), control ]
	coclass Js2n
	{
		[default] dispinterface _DJs2n;
		[default, source] dispinterface _DJs2nEvents;
	};

};
